### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by Mortycio** [pnk2u/More-Feeding-Trough-Variants#1]
![image](https://github.com/user-attachments/assets/d781bce7-15bd-47b1-a442-8bc4110ed8ff)

The game won’t launch as long as this mod is active. As soon as I disable it, the game launches.

mod version: 1.0.1
minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by pnk2u** [comment]
Hi, sorry for the oversight and thanks for reporting it, it should be fixed in the just uploaded version 1.0.2. Let me know if that fixes the issue for you. (:

**Comment by Mortycio** [comment]
It works fine with 1.0.2, thx 😸
